driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_image: chef/chef
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  format: doc

platforms:
- name: debian-7
  driver:
    image: debian:7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install lsb-release -y

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install lsb-release -y

- name: centos-5
  driver:
    image: centos:5
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum install -y which initscripts

- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which systemd-sysv initscripts

- name: fedora-latest
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install yum which systemd-sysv initscripts

- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: opensuse-13.2
  driver:
    image: opensuse:13.2
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive

- name: opensuse-42.1
  driver:
    image: opensuse:42.1
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive

suites:
- name: server
  run_list:
    - recipe[openldap-test::default]
    - recipe[openldap::server]
  attributes:
    openldap:
      rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
      basedn: "dc=example, dc=com"
      server: "ldap.example.com"
      preseed_dir: "/tmp/does_not_exist"
      ssl_cert_source_cookbook: "openldap-test"
      ssl_cert_source_path: "ldap.example.com.pem"
      ssl_key_source_cookbook: "openldap-test"
      ssl_key_source_path: "ldap.example.com.key"
- name: unmanaged_ssl
  run_list:
    - recipe[openldap-test::ssl]
    - recipe[openldap::server]
  attributes:
    openldap:
      rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
      basedn: "dc=example, dc=com"
      server: "ldap.example.com"
      manage_ssl: false
      tls_checkpeer: true
      pam_password: sha
      ssl_dir: "/etc/ldap/ssl"
      ssl_cert: "/etc/ldap/ssl/ldap.example.com.pem"
      ssl_key: "/etc/ldap/ssl/ldap.example.com.pem"
      cafile: "/etc/ldap/ssl/ldap.example.com.pem"
- name: tls_disabled
  run_list:
  - recipe[openldap::server]
  attributes:
   openldap:
     server: localhost
     rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
     tls_enabled: false
     passwd_ou: peeps
     shadow_ou: ninjas
     group_ou: pirates
     automount_ou: barge
